<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="IT-XIONGYW" name="SeleniumUtilTest" tests="6" failures="2" timestamp="11 Oct 2018 08:43:40 GMT" time="45.28" errors="0">
  <testcase name="failureTest" time="5.669" classname="com.selenium.xyouwen.testcase.RegisterTest">
    <failure type="java.lang.AssertionError" message="expected [手机号不能为空] but found [用户名不能为空]">
      <![CDATA[java.lang.AssertionError: expected [手机号不能为空] but found [用户名不能为空]
	at com.selenium.xyouwen.testcase.RegisterTest.failureTest(RegisterTest.java:36)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- failureTest -->
  <testcase name="failureTest" time="2.694" classname="com.selenium.xyouwen.testcase.RegisterTest">
    <failure type="java.lang.AssertionError" message="expected [非法手机号] but found [非法的手机号]">
      <![CDATA[java.lang.AssertionError: expected [非法手机号] but found [非法的手机号]
	at com.selenium.xyouwen.testcase.RegisterTest.failureTest(RegisterTest.java:36)
	at com.sun.proxy.$Proxy0.invoke(Unknown Source)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- failureTest -->
  <testcase name="failureTest" time="2.524" classname="com.selenium.xyouwen.testcase.RegisterTest"/>
  <testcase name="failureTest" time="2.603" classname="com.selenium.xyouwen.testcase.RegisterTest"/>
  <testcase name="failureTest" time="2.631" classname="com.selenium.xyouwen.testcase.RegisterTest"/>
  <testcase name="failureTest" time="2.537" classname="com.selenium.xyouwen.testcase.RegisterTest"/>
</testsuite> <!-- SeleniumUtilTest -->
